# Generated by Django 2.2 on 2019-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('author', models.CharField(default='Anonymous', max_length=50)),
                ('video_url', models.CharField(max_length=100)),
                ('rev_id', models.CharField(max_length=30)),
                ('subtitle_url', models.CharField(max_length=100)),
            ],
        ),
    ]
